[package]
name = "rau"
version = "0.1.0"
authors = ["Tim Newsham <tim.newsham@gmail.com>"]
edition = "2018"

[dependencies]
cpal = "0.13.3"
device_query = "0.2.8"

[workspace]
members = ["filtviz", "phaserviz", "flangerviz", "phaseviz", "genviz", "player"]
