[package]
name = "fftviz"
version = "0.1.0"
edition = "2018"

[dependencies]
rau = { version = "0.1.0", path = ".." }
eframe = "0.13.0"
num-complex = "0.4.0"
wav = "1.0.0"
cpal = "0.13.3"
rustfft = "6.0.1"

